name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:0.6.6-python3.12-bookworm-slim

    steps:
    - name: Install Act dependencies
      if: ${{ env.ACT }}
      run: |
        apt-get update && apt-get install -y nodejs
  
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    
    - name: Set up uv cache
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      with:
        path: |
          ~/.cache/uv
          ~/.uv
        key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv-
    
    - name: Sync environment
      run: |
        uv sync --locked

    - name: Lint with ruff and basedpyright
      run: |
        uv run just check

    - name: Test with pytest
      run: |
        uv run just test
